Entropy and mutual information of Poisson random variables (all units are bits)

In [28]:
import scipy.stats as sts
import numpy as np

# a = 1000, b = 98000, c = 1000    k = 8,  d = 20000
# cbf
lamb = 1000 / 1250
lamb2 = 99000 / 1250
l = lamb * 24000 / 47999
l2 = lamb2 * 24000 / 47999
habc = (2 * sts.skellam.entropy(l, l) + sts.skellam.entropy(l2, l2)) / np.log(2) * 24000
hb_p_c = sts.skellam.entropy(l + l2, l + l2) / np.log(2) * 24000
habc, hb_p_c, habc - hb_p_c

(213797.2579663855, 124993.68051172729, 88803.57745465823)

In [29]:
pmfb = np.empty(60)
for i in range(60):
    pmfb[i] = sts.skellam.pmf(i-30,l2, l2)
pmfa = np.empty(20)
for i in range(20):
    pmfa[i] = sts.skellam.pmf(i-10,l, l)
pmfb, pmfa

(array([0.00015786, 0.00022773, 0.00032463, 0.00045725, 0.00063638,
        0.00087507, 0.00118882, 0.00159556, 0.00211551, 0.00277081,
        0.00358485, 0.00458131, 0.00578291, 0.00720985, 0.00887798,
        0.01079683, 0.0129676 , 0.01538124, 0.0180169 , 0.02084079,
        0.02380588, 0.02685226, 0.02990854, 0.03289426, 0.03572306,
        0.03830673, 0.04055967, 0.04240358, 0.043772  , 0.04461425,
        0.0448986 , 0.04461425, 0.043772  , 0.04240358, 0.04055967,
        0.03830673, 0.03572306, 0.03289426, 0.02990854, 0.02685226,
        0.02380588, 0.02084079, 0.0180169 , 0.01538124, 0.0129676 ,
        0.01079683, 0.00887798, 0.00720985, 0.00578291, 0.00458131,
        0.00358485, 0.00277081, 0.00211551, 0.00159556, 0.00118882,
        0.00087507, 0.00063638, 0.00045725, 0.00032463, 0.00022773]),
 array([1.31764369e-11, 3.29882633e-10, 7.43538105e-09, 1.49034406e-07,
        2.61548314e-06, 3.93804642e-05, 4.94861030e-04, 4.98788767e-03,
        3.79032392e-02, 1.94500135e-01

In [30]:
probs = np.zeros((80, 80))
for i in range(60):
    for j in range(20):
        for k in range(20):
            probs[i+j][i+k] += pmfb[i] * pmfa[j] * pmfa[k]
probs = probs.flatten()        
pentropy = sts.entropy(probs) / np.log(2)
probs.sum(), pentropy

(0.9992009695847776, 7.572900896745241)

In [31]:
habc - hb_p_c, 24000 * pentropy - hb_p_c

(88803.57745465823, 56755.94101015851)

In [32]:
import scipy.stats as sts
import numpy as np

sts.skellam.entropy(1000/1999, 1000/1999) / np.log(2)

2.0240558390456784

In [33]:
total = 20000
lamb = 8000 / total
lamb2 = 99000 * 8 / total
habc = (2 * sts.poisson.entropy(lamb) + sts.poisson.entropy(lamb2)) / np.log(2) * total
hb_p_c = sts.poisson.entropy(lamb + lamb2) / np.log(2) * total
habc, hb_p_c, habc - hb_p_c

(141221.48340269603, 94100.30378550026, 47121.17961719577)

In [34]:
pmfb = np.empty(200)
for i in range(200):
    pmfb[i] = sts.poisson.pmf(i, lamb2)
pmfa = np.empty(20)
for i in range(20):
    pmfa[i] = sts.poisson.pmf(i, lamb)
probs = np.zeros((220, 220))

for i in range(200):
    for j in range(20):
        for k in range(20):
            probs[i+j][i+k] += pmfb[i] * pmfa[j] * pmfa[k]
probs = probs.flatten()        
pentropy = sts.entropy(probs) / np.log(2) * total
probs.sum(), pentropy, pmfa, pmfb

(0.9999999999999969,
 131067.20467572854,
 array([6.70320046e-01, 2.68128018e-01, 5.36256037e-02, 7.15008049e-03,
        7.15008049e-04, 5.72006439e-05, 3.81337626e-06, 2.17907215e-07,
        1.08953607e-08, 4.84238255e-10, 1.93695302e-11, 7.04346553e-13,
        2.34782184e-14, 7.22406721e-16, 2.06401920e-17, 5.50405121e-19,
        1.37601280e-20, 3.23767718e-22, 7.19483818e-24, 1.51470278e-25]),
 array([6.33779980e-18, 2.50976872e-16, 4.96934207e-15, 6.55953153e-14,
        6.49393622e-13, 5.14319748e-12, 3.39451034e-11, 1.92032299e-10,
        9.50559881e-10, 4.18246348e-09, 1.65625554e-08, 5.96251993e-08,
        1.96763158e-07, 5.99370850e-07, 1.69536326e-06, 4.47575901e-06,
        1.10775035e-05, 2.58040671e-05, 5.67689476e-05, 1.18318438e-04,
        2.34270507e-04, 4.41767243e-04, 7.95181037e-04, 1.36909431e-03,
        2.25900561e-03, 3.57826488e-03, 5.44997266e-03, 7.99329324e-03,
        1.13048004e-02, 1.54368999e-02, 2.03767079e-02, 2.60296010e-02,
        3.22116313e-

In [40]:
l = lamb
pentropy - hb_p_c, sts.skellam.entropy(l, l) / np.log(2) * total

(36966.90089022828, 37073.67137335559)

In [36]:
sts.skellam.cdf(2, l, l)

0.9944750436754781

In [37]:
np.log2(5) + 0.2

2.5219280948873624