Entropy and mutual information of Poisson random variables (all units are bits)

In [7]:
from scipy.stats import poisson, skellam
from oniakIO import odats
import numpy as np

result = np.empty(20004)
result[0] = 0
result[1] = 2
result[2] = 20001
for i, v in enumerate(np.linspace(0, 2, 20001)):
    result[i+3] = poisson.entropy(v) / np.log(2)
odats.write_file("../data/poisson_entropy.odat", result)
result



array([0.00000000e+00, 2.00000000e+00, 2.00010000e+04, ...,
       2.45954354e+00, 2.45958464e+00, 2.45962574e+00])

In [11]:
for i, v in enumerate(np.linspace(0, 2, 20001)):
    result[i+3] = skellam.entropy(v/2, v/2) / np.log(2)
result[3] = 0
odats.write_file("../data/skellam_entropy.odat", result)
result

/home/gtnetuser/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: invalid value encountered in _entropy (vectorized)
  outputs = ufunc(*inputs)


array([0.00000000e+00, 2.00000000e+00, 2.00010000e+04, ...,
       2.54077417e+00, 2.54081087e+00, 2.54084757e+00])

In [37]:
pmfs = np.empty(40)
for i in range(40):
    pmfs[i] = poisson.pmf(i, 0.1)
# [-40, 40]
sklm = np.zeros(81)
for i, v in enumerate(pmfs):
    for j in range(41):
        idx = i - j + 40
        if idx < 0 or idx >= 81:
            continue
        sklm[idx] += v * poisson.pmf(j, (100-i) / 999 )
sklm, sklm.sum()

(array([1.04431865e-88, 4.17379664e-86, 1.62616274e-83, 6.17327831e-81,
        2.28184422e-78, 8.20648303e-76, 2.86941846e-73, 9.74634488e-71,
        3.21310491e-68, 1.02717470e-65, 3.18108817e-63, 9.53382001e-61,
        2.76207365e-58, 7.72616453e-56, 2.08400510e-53, 5.41306981e-51,
        1.35193445e-48, 3.24145077e-46, 7.44801340e-44, 1.63695609e-41,
        3.43424314e-39, 6.86177847e-37, 1.30246793e-34, 2.34216541e-32,
        3.97782797e-30, 6.35839156e-28, 9.52844319e-26, 1.33271104e-23,
        1.73088631e-21, 2.07511881e-19, 2.28052008e-17, 2.27844600e-15,
        2.04877787e-13, 1.63761034e-11, 1.14538524e-09, 6.86707339e-08,
        3.43124687e-06, 1.37181228e-04, 4.11475063e-03, 8.23498579e-02,
        8.26789418e-01, 8.23498578e-02, 4.11475064e-03, 1.37181230e-04,
        3.43124693e-06, 6.86707361e-08, 1.14538529e-09, 1.63761045e-11,
        2.04877806e-13, 2.27844626e-15, 2.28052041e-17, 2.07511917e-19,
        1.73088667e-21, 1.33271137e-23, 9.52844595e-26, 6.358393

In [38]:
import scipy
scipy.stats.entropy(sklm) / np.log(2), skellam.entropy(100/999, 100/999) / np.log(2)


(0.8890080307575563, 0.8890077465477842)

In [3]:
import scipy.stats as sts
import numpy as np

# a = 1000, b = 98000, c = 1000    k = 8,  d = 20000
# cbf
habc = (2 * sts.poisson.entropy(0.05) + sts.poisson.entropy(4.9)) / np.log(2) * 20000
hb_p_c = sts.poisson.entropy(4.95) / np.log(2) * 20000
habc, hb_p_c, habc - hb_p_c

(74879.03508717123, 63453.58845807576, 11425.446629095466)

In [10]:
pmfb = np.empty(40)
for i in range(40):
    pmfb[i] = sts.poisson.pmf(i,4.9)
pmfa = np.empty(12)
for i in range(12):
    pmfa[i] = sts.poisson.pmf(i,0.05)
pmfb, pmfa

(array([7.44658307e-03, 3.64882570e-02, 8.93962298e-02, 1.46013842e-01,
        1.78866956e-01, 1.75289617e-01, 1.43153187e-01, 1.00207231e-01,
        6.13769291e-02, 3.34163281e-02, 1.63740008e-02, 7.29387306e-03,
        2.97833150e-03, 1.12260187e-03, 3.92910656e-04, 1.28350814e-04,
        3.93074368e-05, 1.13297906e-05, 3.08422078e-06, 7.95404306e-07,
        1.94874055e-07, 4.54706129e-08, 1.01275456e-08, 2.15760754e-09,
        4.40511539e-10, 8.63402617e-11, 1.62718185e-11, 2.95303374e-12,
        5.16780904e-13, 8.73181527e-14, 1.42619649e-14, 2.25431059e-15,
        3.45191309e-16, 5.12556792e-17, 7.38684788e-18, 1.03415870e-18,
        1.40760490e-19, 1.86412541e-20, 2.40374066e-21, 3.02008442e-22]),
 array([9.51229425e-01, 4.75614712e-02, 1.18903678e-03, 1.98172797e-05,
        2.47715996e-07, 2.47715996e-09, 2.06429997e-11, 1.47449998e-13,
        9.21562485e-16, 5.11979158e-18, 2.55989579e-20, 1.16358900e-22]))

In [15]:
probs = np.zeros((52, 52))
for i in range(40):
    for j in range(12):
        for k in range(12):
            probs[i+j][i+k] += pmfb[i] * pmfa[j] * pmfa[k]
probs = probs.flatten()        
pentropy = sts.entropy(probs) / np.log(2)
probs.sum()

1.0000000000000002

In [16]:
habc - hb_p_c, 20000 * pentropy - hb_p_c

(11425.446629095466, 10950.230996574908)

In [2]:
import scipy.stats as sts
import numpy as np

sts.skellam.entropy(1000/1999, 1000/1999) / np.log(2)

2.0240558390456784