In [1]:
path = "/media/mydrive/distribution/ann-codes/in-memory/EXPERIMENTS/audioN/probing_sequence2.ivecs"
from vecs import *
a = read_legacy_file(path, odat.int32, getoffset=True)
a

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

([array([3000], dtype=int32),
  array([ 26, -18,   7,  12,  35,  19,   4,   3,   0], dtype=int32),
  array([  9,   7,  18, -13,   1,  -1,   8, -13,   1], dtype=int32),
  array([-12,  -4, -16,  -5,   4,   6,  10,  -5,   2], dtype=int32),
  array([ -7,  11, -23,   9, -16,  27, -16,   8,   3], dtype=int32),
  array([  0,  -4,  -9,   0,   7, -19, -16,  -7,   4], dtype=int32),
  array([  9,  11, -16,  19,  -4,  -2,  20,  21,   5], dtype=int32),
  array([  9,  -5,  13,   8, -10, -13, -14,  -1,   6], dtype=int32),
  array([-16,   2,  17,  -4,   2,  17,  -4,  22,   7], dtype=int32),
  array([ 9,  6,  5, 15, 13, -2,  7,  5,  8], dtype=int32),
  array([ 8, -7,  4, -3, -3, 11, 29, -3,  9], dtype=int32),
  array([  5,   1,  -7,   9,  11, -20,  19,  23,  10], dtype=int32),
  array([-4, 10, 11, -4, -8, 15,  8, 23, 11], dtype=int32),
  array([-5, 14,  8,  4, 25, -8,  0,  1, 12], dtype=int32),
  array([ -2, -40,   4,   6,  13, -29,  13,  17,  13], dtype=int32),
  array([  6, -24, -16,  -1, -23,  13,  

In [7]:
a[0].shape

(52587, 1)

In [5]:
a

array([[-3.583506, -3.583506, -3.583506, ..., -3.583506, -3.583506,
        -3.583506],
       [-7.150711, -7.150711, -7.150711, ..., -7.150711, -7.150711,
        -7.150711],
       [-5.33743 , -5.33743 , -5.33743 , ..., -5.33743 , -5.33743 ,
        -5.33743 ],
       ...,
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ]], dtype=float32)

In [4]:
with open(path, "rb") as file:
    while file:
        byte = file.read(4)
        sz = struct.unpack("I", byte)
        byte = file.read(4)
        val = struct.unpack("f", byte)
        print(sz, val)

(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,) (1.0,)
(1,)

error: unpack requires a buffer of 4 bytes

In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,6,5,4,5,6,7,5,4,5,6,7], dtype = np.int8)
a.dtype

dtype('int8')

In [11]:
with open(path, "rb") as file:
    print(file.tell())
    a = np.fromfile(file, dtype=np.int8, count=200000000, offset=0)
    print(a, file.tell())
    a = np.fromfile(file, dtype=np.int8, count=2, offset=0)
    print(a, file.tell())

0
[1 0 0 ... 0 0 0] 120008000
[] 120008000


In [6]:
result = []
buffer = np.empty(120000000, dtype=np.int8)
pos = 0
sum = 0
for i in range(1500000):
    sum += buffer[pos:pos+4].view(np.int32)[0]
    if i % 10000 == 0:
        print(i)
    vec =  buffer[pos+4:pos+80].view(np.int32)
    result.append(vec)
    pos += 80
sum

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
13

0

In [1]:
from vecs import *
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,6,5,4,5,6,7,5,4,5,6,7], dtype = np.int8)
a.dtype
print(np.dtype('int8'))
write_to_file("aaa", a)
b = read_file("aaa")
b

int8


array([[1, 2, 3, 4, 5, 6, 7, 8, 6, 5, 4, 5, 6, 7, 5, 4, 5, 6, 7]],
      dtype=int8)